CREATE DATABASE BookLibrary
GO
USE BookLibrary
GO
CREATE TABLE  BOOK(
	BookCode int IDENTITY, CONSTRAINT PK_Book PRIMARY KEY(BookCode),
	BookTitle varchar(100) NOT NULl,
	Author varchar(50) NOT NULL,
	Editon int,
	BookPrice money,
	Copies int,
	)
	SELECT * FROM BOOK
Go
CREATE TABLE Member(
	MemberCode int IDENTITY,CONSTRAINT PK_Member PRIMARY KEY(MemberCode),
	Name varchar(50) NOT NULL,
	Address varchar(100) NOT NULL,
	PhoneNumber int
	)
	SELECT * FROM Member
	DROP TABLE Member
GO
CREATE TABLE IssueDetails(
	BookCode int, 
	CONSTRAINT fk FOREIGN KEY(BookCode) REFERENCES Book(BookCode),
	MemberCode int, 
	CONSTRAINT fk1 FOREIGN KEY(MemberCode) REFERENCES Member(MemberCode),
	IssueDate datetime,
	ReturnDate datetime
	)
	SELECT * FROM IssueDetails
GO
--XOA BO CAC RANG  BUOC FK cua bang IssusDetail
AlTER TABLE IssueDetails
	DROP CONSTRAINT fk
ALTER TABLE IssueDetails
	DROP CONSTRAINT fk1
GO
--XOA BO RANG BUOC PRIMARY KEY cua bang Member va BOOK
ALTER TABLE Book
	DROP CONSTRAINT PK_BOOK
ALTER TABLE Member
	DROP CONSTRAINT PK_Member
Go
----Them moi RANG BUOC PRIMARY KEY cua bang Member va BOOK
ALTER TABLE BOOK
	ADD CONSTRAINT PK_BOOK PRIMARY KEY(BOOKCODE)
ALTER TABLE Member
	ADD CONSTRAINT PK_Member PRIMARY KEY(MemberCode)
GO
--THEM MOI RANG BUOC KHOA NGOAI CHO BANG ISSUE DETAILS
ALTER TABLE ISSUEDETAILS
	ADD CONSTRAINT FK_BOOK FOREIGN KEY(BOOKCODE) REFERENCES BOOK(BOOKCODE)
ALTER TABLE ISSUEDETAILS
	ADD CONSTRAINT FK_Member FOREIGN KEY(MemberCode) REFERENCES Member(MemberCode)
GO
--THEM RANG BUOC GIA BAN SACH Cho BANG BOOK
ALTER TABLE BOOK
	ADD CONSTRAINT CKC_Price CHECK(BookPrice<200 AND BookPrice>0)
GO
--THEM RANG BUOC DUY NHAT CHO PHONE NUMBER CUA BANG NUMBER
ALTER TABLE MEMBER
	ADD CONSTRAINT UQ_Phone UNIQUE(PhoneNumber)
GO
--THEM RANG BUOC NOT NULL CHO BOOKCODE AND MEMBERCODE trong BANG ISSUEDetails
ALTER TABLE ISSUEDETAILS
	ALTER COLUMN BOOKCODE int NOT NULL
ALTER TABLE ISSUEDETAILS
	ALTER COLUMN MemberCode int NOT NULL
GO
--TAO PRIMARY KEY Cho 2 cot BookCode and MemberCode cho bang IssueDetails
ALTER TABLE ISSUEDETAILS
	ADD CONSTRAINT PK1 PRIMARY KEY(BOOKCODE,MEMBERCODE)
GO
--CHEN DATA cho bang BOOK
INSERT INTO BOOK VALUES('Conan','Mori',1,100,100)
SELECT * FROM BOOK
GO
--CHEN DATA CHO BANG Member
INSERT INTO Member VALUES('Johny English','LonDon',971548331)
GO
--CHEN DATA CHO BANG IssuesDetails
INSERT INTO IssueDetails VALUES(1,1,'1-12-2020 17:59:30','6-12-2020 18:00:00')
SELECT * FROM IssueDetails
GO
ALTER TABLE IssueDetails
	ALTER COLUMN IssueDate datetime2(0)
ALTER TABLE IssueDetails
	ALTER COLUMN ReturnDate datetime2(0)